/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      1000,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6678",
            customMemoryMap:
           [          
                ["MSMCSRAM", 
                     {
                        name: "MSMCSRAM",
                        base: 0x0c000000,                    
                        len: 0x00400000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["L1DSRAM", 
                     {
                        name: "L1DSRAM",
                        base: 0x00F00000,                    
                        len: 0x00008000,                    
                        space: "data",
                        access: "RW",
                     }
                ],
                ["L1PSRAM", 
                     {
                        name: "L1PSRAM",
                        base: 0x00E00000,                    
                        len: 0x00008000,                    
                        space: "code",
                        access: "RWX",
                     }
                ],
                ["L2SRAM", 
                     {
                        name: "L2SRAM",
                        base: 0x00800000,                    
                        len: 0x00080000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR0", 
                     {
                        name: "DDR0",
                        base: 0x80000000,                    
                        len: 0x02e00000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR1", 
                     {
                        name: "DDR1",
                        base: 0x90000000,                    
                        len: 0x10000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR2", 
                     {
                        name: "DDR2",
                        base: 0xa0000000,                    
                        len: 0x10000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR3", 
                     {
                        name: "DDR3",
                        base: 0xb0000000,                    
                        len: 0x10000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR4", 
                     {
                        name: "DDR4",
                        base: 0xc0000000,                    
                        len: 0x10000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR5", 
                     {
                        name: "DDR5",
                        base: 0xd0000000,                    
                        len: 0x10000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR6", 
                     {
                        name: "DDR6",
                        base: 0xe0000000,                    
                        len: 0x10000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR7", 
                     {
                        name: "DDR7",
                        base: 0xf000000,                    
                        len: 0x10000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["InBuffer", 
                     {
                        name: "InBuffer",
                        base: 0x82e00000,                    
                        len: 0x00e00000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["outBuffer", 
                     {
                        name: "outBuffer",
                        base: 0x83c00000,                    
                        len: 0x0c400000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],
          l2Mode: "0k",
          l1PMode: "32k",
          l1DMode: "32k",

    });
    
instance :
    
    override config string codeMemory  = "DDR0";   
    override config string dataMemory  = "DDR0";                                
    override config string stackMemory = "DDR0";

    config String l2Mode = "0k";
    config String l1PMode = "32k";
    config String l1DMode = "32k";
}
